#############################################################################
# Makefile for building: sim-home
# Generated by qmake (2.01a) (Qt 4.8.7) on: Mon Feb 19 10:43:03 2018
# Project:  sim-home.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile sim-home.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Iwidgets -Imodel -Iplanning -Iextras/LAPKT-public/include -Iextras/LAPKT-public/interfaces/agnostic -I.build/.moc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L./lapkt-lib -llapkt -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .build/.obj/

####### Files

SOURCES       = main.cxx \
		model/SimHomeConfig.cxx \
		model/SimHome.cxx \
		widgets/AppWindow.cxx \
		model/Home.cxx \
		model/Room.cxx \
		widgets/HomeRenderer.cxx \
		widgets/RoomView.cxx \
		widgets/GraphicsFactory.cxx \
		model/WalkTo.cxx \
		widgets/GoalSetView.cxx \
		planning/Observer.cxx \
		planning/Goal.cxx \
		widgets/GoalView.cxx \
		widgets/NewGoalDialog.cxx \
		planning/GoalRecognizer.cxx \
		model/OpenDoor.cxx \
		model/CloseDoor.cxx \
		model/Door.cxx \
		model/Agent.cxx \
		model/ItemManager.cxx \
		model/Item.cxx \
		model/Drop.cxx \
		model/PickUp.cxx \
		model/StageProp.cxx \
		model/StagePropAction.cxx \
		model/TurnOn.cxx \
		model/TurnOff.cxx \
		model/LieDown.cxx \
		model/GetOff.cxx \
		model/SitDown.cxx \
		model/GetUp.cxx \
		widgets/ObservationsView.cxx \
		planning/PlanningTask.cxx .build/.moc/moc_SimHomeConfig.cpp \
		.build/.moc/moc_SimHome.cpp \
		.build/.moc/moc_AppWindow.cpp \
		.build/.moc/moc_Home.cpp \
		.build/.moc/moc_Room.cpp \
		.build/.moc/moc_HomeRenderer.cpp \
		.build/.moc/moc_RoomView.cpp \
		.build/.moc/moc_WalkTo.cpp \
		.build/.moc/moc_GoalSetView.cpp \
		.build/.moc/moc_Observer.cpp \
		.build/.moc/moc_Goal.cpp \
		.build/.moc/moc_GoalView.cpp \
		.build/.moc/moc_NewGoalDialog.cpp \
		.build/.moc/moc_GoalRecognizer.cpp \
		.build/.moc/moc_OpenDoor.cpp \
		.build/.moc/moc_CloseDoor.cpp \
		.build/.moc/moc_Door.cpp \
		.build/.moc/moc_Agent.cpp \
		.build/.moc/moc_Item.cpp \
		.build/.moc/moc_Drop.cpp \
		.build/.moc/moc_PickUp.cpp \
		.build/.moc/moc_StageProp.cpp \
		.build/.moc/moc_StagePropAction.cpp \
		.build/.moc/moc_ObservationsView.cpp \
		.build/.moc/moc_PlanningTask.cpp
OBJECTS       = .build/.obj/main.o \
		.build/.obj/SimHomeConfig.o \
		.build/.obj/SimHome.o \
		.build/.obj/AppWindow.o \
		.build/.obj/Home.o \
		.build/.obj/Room.o \
		.build/.obj/HomeRenderer.o \
		.build/.obj/RoomView.o \
		.build/.obj/GraphicsFactory.o \
		.build/.obj/WalkTo.o \
		.build/.obj/GoalSetView.o \
		.build/.obj/Observer.o \
		.build/.obj/Goal.o \
		.build/.obj/GoalView.o \
		.build/.obj/NewGoalDialog.o \
		.build/.obj/GoalRecognizer.o \
		.build/.obj/OpenDoor.o \
		.build/.obj/CloseDoor.o \
		.build/.obj/Door.o \
		.build/.obj/Agent.o \
		.build/.obj/ItemManager.o \
		.build/.obj/Item.o \
		.build/.obj/Drop.o \
		.build/.obj/PickUp.o \
		.build/.obj/StageProp.o \
		.build/.obj/StagePropAction.o \
		.build/.obj/TurnOn.o \
		.build/.obj/TurnOff.o \
		.build/.obj/LieDown.o \
		.build/.obj/GetOff.o \
		.build/.obj/SitDown.o \
		.build/.obj/GetUp.o \
		.build/.obj/ObservationsView.o \
		.build/.obj/PlanningTask.o \
		.build/.obj/moc_SimHomeConfig.o \
		.build/.obj/moc_SimHome.o \
		.build/.obj/moc_AppWindow.o \
		.build/.obj/moc_Home.o \
		.build/.obj/moc_Room.o \
		.build/.obj/moc_HomeRenderer.o \
		.build/.obj/moc_RoomView.o \
		.build/.obj/moc_WalkTo.o \
		.build/.obj/moc_GoalSetView.o \
		.build/.obj/moc_Observer.o \
		.build/.obj/moc_Goal.o \
		.build/.obj/moc_GoalView.o \
		.build/.obj/moc_NewGoalDialog.o \
		.build/.obj/moc_GoalRecognizer.o \
		.build/.obj/moc_OpenDoor.o \
		.build/.obj/moc_CloseDoor.o \
		.build/.obj/moc_Door.o \
		.build/.obj/moc_Agent.o \
		.build/.obj/moc_Item.o \
		.build/.obj/moc_Drop.o \
		.build/.obj/moc_PickUp.o \
		.build/.obj/moc_StageProp.o \
		.build/.obj/moc_StagePropAction.o \
		.build/.obj/moc_ObservationsView.o \
		.build/.obj/moc_PlanningTask.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		sim-home.pro
QMAKE_TARGET  = sim-home
DESTDIR       = 
TARGET        = sim-home

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sim-home.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile sim-home.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile sim-home.pro

dist: 
	@$(CHK_DIR_EXISTS) .build/.obj/sim-home1.0.0 || $(MKDIR) .build/.obj/sim-home1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .build/.obj/sim-home1.0.0/ && $(COPY_FILE) --parents model/SimHomeConfig.hxx model/SimHome.hxx widgets/AppWindow.hxx model/Home.hxx model/Room.hxx widgets/HomeRenderer.hxx widgets/RoomView.hxx widgets/GraphicsFactory.hxx model/WalkTo.hxx widgets/GoalSetView.hxx planning/Observer.hxx planning/Goal.hxx widgets/GoalView.hxx widgets/NewGoalDialog.hxx planning/GoalRecognizer.hxx model/OpenDoor.hxx model/CloseDoor.hxx model/Door.hxx model/Agent.hxx model/ItemManager.hxx model/Item.hxx model/Drop.hxx model/PickUp.hxx model/StageProp.hxx model/StagePropAction.hxx model/TurnOn.hxx model/TurnOff.hxx model/LieDown.hxx model/GetOff.hxx model/SitDown.hxx model/GetUp.hxx widgets/ObservationsView.hxx planning/PlanningTask.hxx .build/.obj/sim-home1.0.0/ && $(COPY_FILE) --parents main.cxx model/SimHomeConfig.cxx model/SimHome.cxx widgets/AppWindow.cxx model/Home.cxx model/Room.cxx widgets/HomeRenderer.cxx widgets/RoomView.cxx widgets/GraphicsFactory.cxx model/WalkTo.cxx widgets/GoalSetView.cxx planning/Observer.cxx planning/Goal.cxx widgets/GoalView.cxx widgets/NewGoalDialog.cxx planning/GoalRecognizer.cxx model/OpenDoor.cxx model/CloseDoor.cxx model/Door.cxx model/Agent.cxx model/ItemManager.cxx model/Item.cxx model/Drop.cxx model/PickUp.cxx model/StageProp.cxx model/StagePropAction.cxx model/TurnOn.cxx model/TurnOff.cxx model/LieDown.cxx model/GetOff.cxx model/SitDown.cxx model/GetUp.cxx widgets/ObservationsView.cxx planning/PlanningTask.cxx .build/.obj/sim-home1.0.0/ && (cd `dirname .build/.obj/sim-home1.0.0` && $(TAR) sim-home1.0.0.tar sim-home1.0.0 && $(COMPRESS) sim-home1.0.0.tar) && $(MOVE) `dirname .build/.obj/sim-home1.0.0`/sim-home1.0.0.tar.gz . && $(DEL_FILE) -r .build/.obj/sim-home1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .build/.moc/moc_SimHomeConfig.cpp .build/.moc/moc_SimHome.cpp .build/.moc/moc_AppWindow.cpp .build/.moc/moc_Home.cpp .build/.moc/moc_Room.cpp .build/.moc/moc_HomeRenderer.cpp .build/.moc/moc_RoomView.cpp .build/.moc/moc_WalkTo.cpp .build/.moc/moc_GoalSetView.cpp .build/.moc/moc_Observer.cpp .build/.moc/moc_Goal.cpp .build/.moc/moc_GoalView.cpp .build/.moc/moc_NewGoalDialog.cpp .build/.moc/moc_GoalRecognizer.cpp .build/.moc/moc_OpenDoor.cpp .build/.moc/moc_CloseDoor.cpp .build/.moc/moc_Door.cpp .build/.moc/moc_Agent.cpp .build/.moc/moc_Item.cpp .build/.moc/moc_Drop.cpp .build/.moc/moc_PickUp.cpp .build/.moc/moc_StageProp.cpp .build/.moc/moc_StagePropAction.cpp .build/.moc/moc_ObservationsView.cpp .build/.moc/moc_PlanningTask.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .build/.moc/moc_SimHomeConfig.cpp .build/.moc/moc_SimHome.cpp .build/.moc/moc_AppWindow.cpp .build/.moc/moc_Home.cpp .build/.moc/moc_Room.cpp .build/.moc/moc_HomeRenderer.cpp .build/.moc/moc_RoomView.cpp .build/.moc/moc_WalkTo.cpp .build/.moc/moc_GoalSetView.cpp .build/.moc/moc_Observer.cpp .build/.moc/moc_Goal.cpp .build/.moc/moc_GoalView.cpp .build/.moc/moc_NewGoalDialog.cpp .build/.moc/moc_GoalRecognizer.cpp .build/.moc/moc_OpenDoor.cpp .build/.moc/moc_CloseDoor.cpp .build/.moc/moc_Door.cpp .build/.moc/moc_Agent.cpp .build/.moc/moc_Item.cpp .build/.moc/moc_Drop.cpp .build/.moc/moc_PickUp.cpp .build/.moc/moc_StageProp.cpp .build/.moc/moc_StagePropAction.cpp .build/.moc/moc_ObservationsView.cpp .build/.moc/moc_PlanningTask.cpp
.build/.moc/moc_SimHomeConfig.cpp: model/SimHomeConfig.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/SimHomeConfig.hxx -o .build/.moc/moc_SimHomeConfig.cpp

.build/.moc/moc_SimHome.cpp: model/SimHome.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/SimHome.hxx -o .build/.moc/moc_SimHome.cpp

.build/.moc/moc_AppWindow.cpp: widgets/AppWindow.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/AppWindow.hxx -o .build/.moc/moc_AppWindow.cpp

.build/.moc/moc_Home.cpp: model/Home.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/Home.hxx -o .build/.moc/moc_Home.cpp

.build/.moc/moc_Room.cpp: model/Room.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/Room.hxx -o .build/.moc/moc_Room.cpp

.build/.moc/moc_HomeRenderer.cpp: widgets/HomeRenderer.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/HomeRenderer.hxx -o .build/.moc/moc_HomeRenderer.cpp

.build/.moc/moc_RoomView.cpp: widgets/RoomView.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/RoomView.hxx -o .build/.moc/moc_RoomView.cpp

.build/.moc/moc_WalkTo.cpp: model/WalkTo.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/WalkTo.hxx -o .build/.moc/moc_WalkTo.cpp

.build/.moc/moc_GoalSetView.cpp: widgets/GoalView.hxx \
		widgets/ObservationsView.hxx \
		widgets/GoalSetView.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/GoalSetView.hxx -o .build/.moc/moc_GoalSetView.cpp

.build/.moc/moc_Observer.cpp: planning/Goal.hxx \
		widgets/GoalView.hxx \
		planning/Observer.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) planning/Observer.hxx -o .build/.moc/moc_Observer.cpp

.build/.moc/moc_Goal.cpp: planning/Goal.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) planning/Goal.hxx -o .build/.moc/moc_Goal.cpp

.build/.moc/moc_GoalView.cpp: widgets/GoalView.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/GoalView.hxx -o .build/.moc/moc_GoalView.cpp

.build/.moc/moc_NewGoalDialog.cpp: widgets/NewGoalDialog.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/NewGoalDialog.hxx -o .build/.moc/moc_NewGoalDialog.cpp

.build/.moc/moc_GoalRecognizer.cpp: planning/Goal.hxx \
		planning/PlanningTask.hxx \
		planning/GoalRecognizer.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) planning/GoalRecognizer.hxx -o .build/.moc/moc_GoalRecognizer.cpp

.build/.moc/moc_OpenDoor.cpp: model/OpenDoor.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/OpenDoor.hxx -o .build/.moc/moc_OpenDoor.cpp

.build/.moc/moc_CloseDoor.cpp: model/CloseDoor.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/CloseDoor.hxx -o .build/.moc/moc_CloseDoor.cpp

.build/.moc/moc_Door.cpp: model/Door.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/Door.hxx -o .build/.moc/moc_Door.cpp

.build/.moc/moc_Agent.cpp: model/Agent.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/Agent.hxx -o .build/.moc/moc_Agent.cpp

.build/.moc/moc_Item.cpp: model/Item.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/Item.hxx -o .build/.moc/moc_Item.cpp

.build/.moc/moc_Drop.cpp: model/Drop.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/Drop.hxx -o .build/.moc/moc_Drop.cpp

.build/.moc/moc_PickUp.cpp: model/PickUp.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/PickUp.hxx -o .build/.moc/moc_PickUp.cpp

.build/.moc/moc_StageProp.cpp: model/StageProp.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/StageProp.hxx -o .build/.moc/moc_StageProp.cpp

.build/.moc/moc_StagePropAction.cpp: model/StagePropAction.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) model/StagePropAction.hxx -o .build/.moc/moc_StagePropAction.cpp

.build/.moc/moc_ObservationsView.cpp: widgets/ObservationsView.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widgets/ObservationsView.hxx -o .build/.moc/moc_ObservationsView.cpp

.build/.moc/moc_PlanningTask.cpp: planning/PlanningTask.hxx
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) planning/PlanningTask.hxx -o .build/.moc/moc_PlanningTask.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: .build/.ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) .build/.ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.build/.obj/main.o: main.cxx model/SimHomeConfig.hxx \
		model/SimHome.hxx \
		widgets/AppWindow.hxx \
		planning/Observer.hxx \
		planning/Goal.hxx \
		widgets/GoalView.hxx \
		widgets/GoalSetView.hxx \
		widgets/ObservationsView.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/main.o main.cxx

.build/.obj/SimHomeConfig.o: model/SimHomeConfig.cxx model/SimHomeConfig.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/SimHomeConfig.o model/SimHomeConfig.cxx

.build/.obj/SimHome.o: model/SimHome.cxx model/SimHome.hxx \
		model/Home.hxx \
		widgets/RoomView.hxx \
		model/Room.hxx \
		model/Door.hxx \
		model/Agent.hxx \
		model/StageProp.hxx \
		planning/Observer.hxx \
		planning/Goal.hxx \
		widgets/GoalView.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/SimHome.o model/SimHome.cxx

.build/.obj/AppWindow.o: widgets/AppWindow.cxx widgets/AppWindow.hxx \
		widgets/HomeRenderer.hxx \
		widgets/RoomView.hxx \
		widgets/GoalSetView.hxx \
		widgets/GoalView.hxx \
		widgets/ObservationsView.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/AppWindow.o widgets/AppWindow.cxx

.build/.obj/Home.o: model/Home.cxx model/Home.hxx \
		model/Room.hxx \
		model/Door.hxx \
		model/ItemManager.hxx \
		model/Item.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Home.o model/Home.cxx

.build/.obj/Room.o: model/Room.cxx model/Room.hxx \
		model/WalkTo.hxx \
		model/PickUp.hxx \
		model/Drop.hxx \
		planning/Observer.hxx \
		planning/Goal.hxx \
		widgets/GoalView.hxx \
		model/Door.hxx \
		model/OpenDoor.hxx \
		model/CloseDoor.hxx \
		model/Agent.hxx \
		model/Item.hxx \
		model/ItemManager.hxx \
		model/StageProp.hxx \
		model/StagePropAction.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Room.o model/Room.cxx

.build/.obj/HomeRenderer.o: widgets/HomeRenderer.cxx widgets/HomeRenderer.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/HomeRenderer.o widgets/HomeRenderer.cxx

.build/.obj/RoomView.o: widgets/RoomView.cxx widgets/RoomView.hxx \
		widgets/GraphicsFactory.hxx \
		model/Room.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/RoomView.o widgets/RoomView.cxx

.build/.obj/GraphicsFactory.o: widgets/GraphicsFactory.cxx widgets/GraphicsFactory.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/GraphicsFactory.o widgets/GraphicsFactory.cxx

.build/.obj/WalkTo.o: model/WalkTo.cxx model/WalkTo.hxx \
		model/Room.hxx \
		model/Door.hxx \
		model/Agent.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/WalkTo.o model/WalkTo.cxx

.build/.obj/GoalSetView.o: widgets/GoalSetView.cxx widgets/GoalSetView.hxx \
		widgets/GoalView.hxx \
		widgets/ObservationsView.hxx \
		widgets/NewGoalDialog.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/GoalSetView.o widgets/GoalSetView.cxx

.build/.obj/Observer.o: planning/Observer.cxx planning/Observer.hxx \
		planning/Goal.hxx \
		widgets/GoalView.hxx \
		planning/GoalRecognizer.hxx \
		planning/PlanningTask.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Observer.o planning/Observer.cxx

.build/.obj/Goal.o: planning/Goal.cxx planning/Goal.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Goal.o planning/Goal.cxx

.build/.obj/GoalView.o: widgets/GoalView.cxx widgets/GoalView.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/GoalView.o widgets/GoalView.cxx

.build/.obj/NewGoalDialog.o: widgets/NewGoalDialog.cxx widgets/NewGoalDialog.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/NewGoalDialog.o widgets/NewGoalDialog.cxx

.build/.obj/GoalRecognizer.o: planning/GoalRecognizer.cxx planning/GoalRecognizer.hxx \
		planning/Goal.hxx \
		planning/PlanningTask.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/GoalRecognizer.o planning/GoalRecognizer.cxx

.build/.obj/OpenDoor.o: model/OpenDoor.cxx model/OpenDoor.hxx \
		model/Door.hxx \
		model/Room.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/OpenDoor.o model/OpenDoor.cxx

.build/.obj/CloseDoor.o: model/CloseDoor.cxx model/CloseDoor.hxx \
		model/Door.hxx \
		model/Room.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/CloseDoor.o model/CloseDoor.cxx

.build/.obj/Door.o: model/Door.cxx model/Door.hxx \
		planning/Observer.hxx \
		planning/Goal.hxx \
		widgets/GoalView.hxx \
		model/Room.hxx \
		model/OpenDoor.hxx \
		model/CloseDoor.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Door.o model/Door.cxx

.build/.obj/Agent.o: model/Agent.cxx model/Agent.hxx \
		model/Item.hxx \
		model/ItemManager.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Agent.o model/Agent.cxx

.build/.obj/ItemManager.o: model/ItemManager.cxx model/ItemManager.hxx \
		model/Item.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/ItemManager.o model/ItemManager.cxx

.build/.obj/Item.o: model/Item.cxx model/Item.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Item.o model/Item.cxx

.build/.obj/Drop.o: model/Drop.cxx model/Drop.hxx \
		model/Room.hxx \
		model/Agent.hxx \
		model/Item.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/Drop.o model/Drop.cxx

.build/.obj/PickUp.o: model/PickUp.cxx model/PickUp.hxx \
		model/Room.hxx \
		model/Agent.hxx \
		model/Item.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/PickUp.o model/PickUp.cxx

.build/.obj/StageProp.o: model/StageProp.cxx model/StageProp.hxx \
		model/StagePropAction.hxx \
		model/Room.hxx \
		model/Agent.hxx \
		planning/Observer.hxx \
		planning/Goal.hxx \
		widgets/GoalView.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/StageProp.o model/StageProp.cxx

.build/.obj/StagePropAction.o: model/StagePropAction.cxx model/StagePropAction.hxx \
		model/Agent.hxx \
		model/Room.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/StagePropAction.o model/StagePropAction.cxx

.build/.obj/TurnOn.o: model/TurnOn.cxx model/TurnOn.hxx \
		model/StagePropAction.hxx \
		model/Agent.hxx \
		model/Room.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/TurnOn.o model/TurnOn.cxx

.build/.obj/TurnOff.o: model/TurnOff.cxx model/TurnOff.hxx \
		model/StagePropAction.hxx \
		model/Agent.hxx \
		model/Room.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/TurnOff.o model/TurnOff.cxx

.build/.obj/LieDown.o: model/LieDown.cxx model/LieDown.hxx \
		model/StagePropAction.hxx \
		model/Agent.hxx \
		model/Room.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/LieDown.o model/LieDown.cxx

.build/.obj/GetOff.o: model/GetOff.cxx model/GetOff.hxx \
		model/StagePropAction.hxx \
		model/Agent.hxx \
		model/Room.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/GetOff.o model/GetOff.cxx

.build/.obj/SitDown.o: model/SitDown.cxx model/SitDown.hxx \
		model/StagePropAction.hxx \
		model/Agent.hxx \
		model/Room.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/SitDown.o model/SitDown.cxx

.build/.obj/GetUp.o: model/GetUp.cxx model/GetUp.hxx \
		model/StagePropAction.hxx \
		model/Agent.hxx \
		model/Room.hxx \
		model/StageProp.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/GetUp.o model/GetUp.cxx

.build/.obj/ObservationsView.o: widgets/ObservationsView.cxx widgets/ObservationsView.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/ObservationsView.o widgets/ObservationsView.cxx

.build/.obj/PlanningTask.o: planning/PlanningTask.cxx planning/PlanningTask.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/PlanningTask.o planning/PlanningTask.cxx

.build/.obj/moc_SimHomeConfig.o: .build/.moc/moc_SimHomeConfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_SimHomeConfig.o .build/.moc/moc_SimHomeConfig.cpp

.build/.obj/moc_SimHome.o: .build/.moc/moc_SimHome.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_SimHome.o .build/.moc/moc_SimHome.cpp

.build/.obj/moc_AppWindow.o: .build/.moc/moc_AppWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_AppWindow.o .build/.moc/moc_AppWindow.cpp

.build/.obj/moc_Home.o: .build/.moc/moc_Home.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Home.o .build/.moc/moc_Home.cpp

.build/.obj/moc_Room.o: .build/.moc/moc_Room.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Room.o .build/.moc/moc_Room.cpp

.build/.obj/moc_HomeRenderer.o: .build/.moc/moc_HomeRenderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_HomeRenderer.o .build/.moc/moc_HomeRenderer.cpp

.build/.obj/moc_RoomView.o: .build/.moc/moc_RoomView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_RoomView.o .build/.moc/moc_RoomView.cpp

.build/.obj/moc_WalkTo.o: .build/.moc/moc_WalkTo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_WalkTo.o .build/.moc/moc_WalkTo.cpp

.build/.obj/moc_GoalSetView.o: .build/.moc/moc_GoalSetView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_GoalSetView.o .build/.moc/moc_GoalSetView.cpp

.build/.obj/moc_Observer.o: .build/.moc/moc_Observer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Observer.o .build/.moc/moc_Observer.cpp

.build/.obj/moc_Goal.o: .build/.moc/moc_Goal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Goal.o .build/.moc/moc_Goal.cpp

.build/.obj/moc_GoalView.o: .build/.moc/moc_GoalView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_GoalView.o .build/.moc/moc_GoalView.cpp

.build/.obj/moc_NewGoalDialog.o: .build/.moc/moc_NewGoalDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_NewGoalDialog.o .build/.moc/moc_NewGoalDialog.cpp

.build/.obj/moc_GoalRecognizer.o: .build/.moc/moc_GoalRecognizer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_GoalRecognizer.o .build/.moc/moc_GoalRecognizer.cpp

.build/.obj/moc_OpenDoor.o: .build/.moc/moc_OpenDoor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_OpenDoor.o .build/.moc/moc_OpenDoor.cpp

.build/.obj/moc_CloseDoor.o: .build/.moc/moc_CloseDoor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_CloseDoor.o .build/.moc/moc_CloseDoor.cpp

.build/.obj/moc_Door.o: .build/.moc/moc_Door.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Door.o .build/.moc/moc_Door.cpp

.build/.obj/moc_Agent.o: .build/.moc/moc_Agent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Agent.o .build/.moc/moc_Agent.cpp

.build/.obj/moc_Item.o: .build/.moc/moc_Item.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Item.o .build/.moc/moc_Item.cpp

.build/.obj/moc_Drop.o: .build/.moc/moc_Drop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_Drop.o .build/.moc/moc_Drop.cpp

.build/.obj/moc_PickUp.o: .build/.moc/moc_PickUp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_PickUp.o .build/.moc/moc_PickUp.cpp

.build/.obj/moc_StageProp.o: .build/.moc/moc_StageProp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_StageProp.o .build/.moc/moc_StageProp.cpp

.build/.obj/moc_StagePropAction.o: .build/.moc/moc_StagePropAction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_StagePropAction.o .build/.moc/moc_StagePropAction.cpp

.build/.obj/moc_ObservationsView.o: .build/.moc/moc_ObservationsView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_ObservationsView.o .build/.moc/moc_ObservationsView.cpp

.build/.obj/moc_PlanningTask.o: .build/.moc/moc_PlanningTask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .build/.obj/moc_PlanningTask.o .build/.moc/moc_PlanningTask.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

